# Compiler
CC := cc

# Flags
CFLAGS  := -std=c99 -Wall -Wextra -Wpedantic -g -Isrc -MMD -MP
LDFLAGS :=

# Directories
SRC_DIR   := src
BUILD_DIR := build

# Output binary
BIN := liminal

# Find all source files
SRCS := $(shell find $(SRC_DIR) -name '*.c')

# Object files mirror source tree
OBJS := $(SRCS:%.c=$(BUILD_DIR)/%.o)

# Dependency files (.d generated by compiler)
DEPS := $(OBJS:.o=.d)

.PHONY: all clean run

all: $(BIN)

# Link step
$(BIN): $(OBJS)
	$(CC) $(OBJS) -o $@ $(LDFLAGS)

# Compile step
$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Include auto-generated dependencies
-include $(DEPS)

run: $(BIN)
	./$(BIN)

clean:
	rm -rf $(BUILD_DIR) $(BIN)
